server:
  port: 8762 # 本服务所使用的端口号
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.110:8761/eureka/ # 生产环境
      
spring:
  application:
    name: eshop-product-service # 自己要注册的微服务名称
  datasource:          # 配置Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.103:3306/eshop?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC # 生产环境
    username: root
    password: root
    
  rabbitmq: # 配置RabbitMQ的连接信息
    host: 192.168.1.103 # 生产环境
    port: 5672  # RabbitMQ监听的端口
    username: rabbitadmin
    password: 123456